import fs from "node:fs";
import path from "node:path";
import { getPages } from "./utils/get-pages.ts";
import { BUILD_CONFIG } from "./config.ts";

async function typegen() {
    const pages = await getPages(BUILD_CONFIG.DIR);

    const contents = `// AUTO-GENERATED by typegen.ts
    export type __PagesType = ${JSON.stringify(pages, null, 4)};

    export type __CurrentRoute = keyof __PagesType;
    `;

    fs.mkdirSync(path.dirname(BUILD_CONFIG.TYPEGEN_OUT_FILE), { recursive: true });
    fs.writeFileSync(BUILD_CONFIG.TYPEGEN_OUT_FILE, contents);
}

typegen();
