name: Github Pages CI

on: workflow_call

jobs:
    build_and_upload_artifacts:
        uses: ./github/workflows/github-pages/build-and-upload-artifacts.yml

    type_check:
        needs: build_and_upload_artifacts
        uses: ./github/workflows/github-pages/deploy.yml
        permissions:
            pages: write
            id-token: write
