name: Type check

on: workflow_call

jobs:
    type_check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Setup node
              uses: actions/setup-node@v7
              with:
                  node-version: latest

            - name: Setup pnpm
              uses: pnpm/action-setup@v6
              with:
                  version: latest

            - name: Install dependencies
              run: pnpm install

            - name: Generate types
              run: pnpm run typegen

            - name: Type check
              run: pnpm run type-check
